import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignIn, SignUp, UserButton } from "@clerk/nextjs";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const font = Open_Sans({ subsets :['latin']})

export const metadata: Metadata = {
  title: "Gatherly",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${font.className} ${font.className} antialiased`}>
            {/* {children} */}
          <SignedIn>{children}
            <UserButton />
          </SignedIn>
           <SignedOut>
             <SignUp />
           </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}

// import { ClerkProvider, SignedIn, SignedOut, RedirectToSignIn } from '@clerk/nextjs'

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html>
//       <body className={`${font.className} ${font.className} antialiased`}>
//         <ClerkProvider>
//           <SignedIn>{children}</SignedIn>
//           <SignedOut>
//             <RedirectToSignIn />
//           </SignedOut>
//         </ClerkProvider>
//       </body>
//     </html>
//   )
// }




